name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          targets: wasm32-unknown-unknown
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ hashFiles('Cargo.lock') }}
      - name: Run CI script
        run: bash ci.sh
